Add handling for rate limiting
plneto/TvMaze.Api.Client pull request #15
Opened 2021-03-15 22:05 UTC by Smith00101010

The API defines rate limits and will respond with a 429 status code if too many requests are made in a short time (https://www.tvmaze.com/api#rate-limiting). As this is normal behavior of the API it should be possible to define a way to deal with it. For that I introduced the IRateLimitingStrategy interface which allows to define, how the client should deal with this case.

The first implementation just does the same as until now and the normal exception is thrown, but the second implementation uses the very popular Polly library to implement retries wit a waiting interval. As the interface is public, users could inject their own implementations, if they have different needs.

The only thing I don't quite like are the tests, as it can take some time to trigger the rate limiting because cached responses are not counted against the limit but I have currently no idea about how to better test it.

2021-03-16 17:40 UTC, Smith00101010 commented
I now implemented the test as a more abstract but reliable unit test

2021-03-16 22:32 UTC, plneto requested changes

2021-03-16 22:32 UTC, plneto commented on src/TvMaze.Api.Client.Integration.Tests/RateLimitingStrategyUnitTests.cs
> +    public class RateLimitingStrategyUnitTests
I think we can put these tests in a separate project, e.g. `TvMaze.Api.Client.Tests`, then we can run them in the CI pipeline.

UPDATE:
I've just merged my branch where I added Flurl and I also created this project for unit tests. You can easily mock the requests and it's easy to arrange the tests to return a 429 response now.

2021-03-16 22:32 UTC, plneto commented on src/TvMaze.Api.Client/Configuration/RetryRateLimitingStrategy.cs
> +            : this(5, TimeSpan.FromSeconds(3))
Can you move these default values to constants so we know what the numbers mean? Something like `DefaultNumberOfRetries` and `DefaultRetryInterval`.

2021-03-16 22:32 UTC, plneto commented on src/TvMaze.Api.Client/Configuration/RetryRateLimitingStrategy.cs
> +                .HandleResult<HttpResponseMessage>(message => message.StatusCode == (HttpStatusCode)429)
Can you move the response code to a constant as well? Unfortunately the `HttpStatusCode.TooManyRequests` enum is only available on `netstandard2.1`

2021-03-16 22:48 UTC, plneto commented
I've been trying to find a better way to test the endpoints without relying on integration tests and I came across a library called Flurl (https://flurl.dev/). Are you familiar with it? It would be nice to have a more testable HTTP client so we can mock all the responses that we need.

2021-03-17 19:40 UTC, Smith00101010 commented
I rebased the branch onto your changes and implemented your suggestions

2021-03-17 19:50 UTC, plneto commented
> I rebased the branch onto your changes and implemented your suggestions

Thank you 👍

2021-03-17 19:50 UTC, merged